-- 1. Revenue by Gender – Compared total revenue generated by male vs. female customers. 

SELECT * FROM customer_shopping LIMIT 20;
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer_shopping
GROUP BY gender;

-- 2.High-Spending Discount Users – Identified customers who used discounts but still spent above the average purchase amount. 

SELECT customer_id, purchase_amount
FROM customer_shopping
WHERE discount_applied = 'yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_shopping);

-- 3.Top 5 Products by Rating – Found products with the highest average review ratings. 

SELECT item_purchased, ROUND(AVG(review_rating),2) AS "Average Product Rating"
FROM customer_shopping
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- 4. Shipping Type Comparison – Compared average purchase amounts between Standard and Express shipping. 

SELECT ROUND(AVG(purchase_amount),2) AS 'Average Purchase Amount', shipping_type
FROM customer_shopping
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status, 
		COUNT(customer_id) AS total_customers, 
		ROUND(AVG(purchase_amount),2) AS 'Avg_spend', 
		SUM(purchase_amount) AS 'total_revenue'
FROM customer_shopping
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased, ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS discount_rate
FROM customer_shopping
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type AS (
SELECT previous_purchases, customer_id,
CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer_shopping
    )
SELECT customer_segment, count(*) AS 'Number of Customers'
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 

WITH item_counts AS(
SELECT category, 
item_purchased, 
count(customer_id) AS total_orders,
row_number() OVER (partition by category order by count(customer_id) DESC) AS item_rank
from customer_shopping
group by category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer_shopping
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 

SELECT age_group,
SUM(purchase_amount) AS revenue_contributioncustomer_shopping
FROM customer_shopping
GROUP BY age_group
ORDER BY revenue_contribution desc;
